/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_libiperf_WRAP_H_
#define SWIG_libiperf_WRAP_H_

class SwigDirector_iPerfResultCallbacks : public iPerfResultCallbacks, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_iPerfResultCallbacks(JNIEnv *jenv);
    virtual ~SwigDirector_iPerfResultCallbacks();
    virtual void onIntermediateResult(double bits, bool download);
    virtual void onSummaryResult(double totalBits, int count, bool download);
public:
    bool swig_overrides(int n) {
      return (n < 2 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<2> swig_override;
};

class SwigDirector_iPerf : public iPerf, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_iPerf(JNIEnv *jenv, char *hostname, int port, char *streamTemplate, int duration, int interval, bool download);
    virtual ~SwigDirector_iPerf();
    virtual void onIntermediateResult(double bits, bool download);
    virtual void onSummaryResult(double totalBits, int count, bool download);
public:
    bool swig_overrides(int n) {
      return (n < 2 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<2> swig_override;
};


#endif
